### ISSUE TITLE
set working directory for node

### ISSUE THREAD

**Issue by Xenorage** [TracerBench/chrome-debugging-client#58]
As far as I know there is no command line option for node to change the work dir.
Only way to change it is to { cwd: 'path'} variable in execa options. This api cant pass this option to execa, right? Or am I missing something?

**Comment by krisselden** [comment]
@Xenorage happy to add that as a SpawnOption, was trying not to expose the internals of execa.

**Comment by Xenorage** [comment]
Thx, that would be great! Was thinking to do it myself but I'am lazy :P
Should be implemented so you can pass all exaca options. Who knows what people will need...

**Comment by krisselden** [comment]
@Xenorage specific process spawn options interfere are not compatible with the specific protocol transport method, which is why I didn't just assign the options or expose everything.  I'm open to rethinking how to do this to make it more flexible, I've trying to keep the layers of this library separate, majority of the actual code is in @tracerbench/protocol-transport which has no expectations of environment, can be used in a browser or node or whatever runs JS and can adapt something to the message-transport interface.
